# Generated by Django 4.2.3 on 2023-08-14 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(default=0, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
